services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     - db
  #   networks:
  #     - my_network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - my_network
  # redis-bull:
  #   image: redis
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT}"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - my_network

networks:
  my_network:
    driver: bridge

volumes:
  dbdata: {}
  # redis_data: {}
  # redis_websocket_data: {}

